### ISSUE TITLE
Render preact component to string in NodeJS environment

### ISSUE THREAD

**Issue by bagr001** [preactjs/preact-render-to-string#160]
Hi, in my development workflow I am trying to render preact component to string in NodeJS environment but with no luck.
I am using all latest preact packages and bundling all with webpack. I have tried different webpack configurations (output as `umd` or `commonjs`) but I always end up with this error: `TypeError: Cannot read property '__H' of undefined`. It seems there is somewhere problem with hooks. I also found that this error has already been discussed here before. Has anyone tried this before or can help me please? Thanks.

Here is a scipt I would like to use to render component to string:

```
const preact = require('preact');
const render = require('preact-render-to-string');
const BianoReact = require('../dist/js/MyLib.js');

console.log(render(preact.h(MyLib..MyComponent({}))));
```

**Comment by marvinhagemeister** [comment]
1) Make sure that the webpack bundle doesn't include Preact, otherwise there will be two copies of it loaded at the same time: One from webpack and one in Node. Hooks require a Singleton by design, which is why multiple copies of Preact breaks hooks.

2) Don't call component constructors yourself. They need to be called by createElement/h similar to how it's done with React.

```js
// Wrong
render(preact.h(MyLib.MyComponent({})));

// Correct
render(preact.h(MyLib.MyComponent, {}));
```

**Comment by bagr001** [comment]
@marvinhagemeister Thank you!!! It works like a charm :-)
