### ISSUE TITLE
Don't escape HTML &-entities in literal text

### ISSUE THREAD

**Issue by broofa** [preactjs/preact-render-to-string#176]
See also https://github.com/developit/htm/issues/76

According to the [JSX docs](https://shripadk.github.io/react/docs/jsx-gotchas.html), "You can insert HTML entities within literal text in JSX", but this does not appear to work because of how &'s are escaped in the [encodeEntities() method](https://github.com/preactjs/preact/blob/60b538cca55a49db3ea441903930a3fc0c5dfa11/test/_util/helpers.js#L48-L50).

Could this method be made to ignore &'s that are part of valid html character entities?  I could put a PR together, but want to get a sense of how receptive you are to this.  (And I suspect I may be missing other, important requirements.)

**Comment by developit** [comment]
This actually is an HTM issue. JSX converts html-encoded entities to UTF8 ([see example](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=PTAEAECsGcA9QBYCgA8ATAlgNwHwENQAyPAWwAcBuUAIxWE1wqSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.12.14&externalPlugins=)), it's not part of VDOM rendering.

Because of this, `preact-render-to-string` is never passed `"a &amp; b"` and expected to render `"a & b"`. That would be a mismatch for how JSXText works on the client, where html-encoded entities in text are rendered as-is. This is a little confusing, since obviously entities do get decoded, just as the link above shows this actually happens during JSX compilation.

I think developit/htm#76 describes this issue pretty well though. From a Preact standpoint, neither the client-side renderer nor the server-side renderer should be handling this, since both treat JSXText as string literals (to match all other VDOM libraries). It would be too strange/broken if `<div>{"&"}</div>` and `<div>{"&amp;"}</div>` rendered the same output.

~~

For context on the HTM issue: the reason this hasn't been done is because HTML entity decoding is disproportionately expensive for no material gain. Entity decoding can only be implemented using a character mapping that is larger than HTM and Preact combined (along with a decent bit of conversion logic). Here's the mapping Babel's JSX transform uses:
https://github.com/babel/babel/blob/328ef420a45d63a12434a07f939ff592e9832727/packages/babel-parser/src/plugins/jsx/xhtml.js

When running in a browser context, HTM _could_ technically use the DOM to perform this conversion, which is slow but cacheable. Personally though, I'm not a huge fan of any of the approaches. There are two use-cases for HTM decoding HTML entities:
1. to be a 1:1 compile target for JSX - this is already handled by the `jsx-to-htm` Babel transform, does entity decoding.
2. using HTM as a general-purposes HTML-to-VDOM converter - something it just isn't built for.

For the second use-case, at some point I would like to extract the old HTM 1 codebase, which was built on DOMParser and actually set out to cater to handling the full spectrum of HTML use-cases. In the meantime, `preact-markup` is a decent approximation of the same approach (albeit slower and larger).

**Comment by shingo-nakanishi** [comment]
I'm not very good at English, so I don't really understand what's going on, but I'm having trouble escaping the following results.

Code:
```
const outRender = render(html`<link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet" />`)
console.log(outRender)
```

Result:
```
<link href="https://fonts.googleapis.com/css2?family=Lora&amp;display=swap" rel="stylesheet" />
```

Is there an option to cancel the escaping?

**Comment by rschristian** [comment]
Should this be occurring in props too? For example,

```jsx
render(h('div', { class: 'flex(& col)' }));

// Results in

<div class="flex(&amp; col)"></div>
```

which is rather unexpected.

**Comment by renhiyama** [comment]
any updates on this?

**Comment by torchsmith** [comment]
bump

**Comment by broofa** [comment]
[Closing out issues I authored that appear to be stagnant.]

**Comment by torchsmith** [comment]
@broofa please re-open.

**Comment by broofa** [comment]
@torchsmith: No. This issue is 2+ years old and conversation petered out at [in essence], "**Won't fix**".

If you want this reopened, make the case for that to the maintainers.  I've moved on to other things and have unsubscribed from this issue.

**Comment by brandon-lb** [comment]
Between this and https://github.com/preactjs/preact-render-to-string/issues/273, I think I'm going to revert back to using plain old react.

**Comment by brandon-lb** [comment]
I fixed it with: `<style dangerouslySetInnerHTML={{ __html: myString }} />` though
