### ISSUE TITLE
Throw more descriptive error

### ISSUE THREAD

**Issue by lohfu** [preactjs/preact-render-to-string#68]
Currently a string is thrown instead of an error at: <https://github.com/developit/preact-render-to-string/blob/ef7b0a260f3bf834a7deaf4cb5e8016610c57ed4/src/index.js#L149-L150>

This leads to very uninformative lines such as:

```
<[object Object] cars="[object Object],[object Object],[object Object],[object Object]">
```

Is there a reason why a proper error is not thrown?

**Comment by developit** [comment]
@lohfu for size reasons. Serializing an arbitrary Virtual DOM element is actually quite a lengthy exercise, including serializing potentially infinitely nested data structures with circular references.

In your case it looks like you may be rendering a Component as a String, which makes me wonder - was this using a test framework and thus `preact-render-to-string/jsx`?  If so I think we could explore the option of fixing serialization in that submodule since it's designed specifically for testing/debugging purposes.

**Comment by lohfu** [comment]
@developit to be honest i cant remember exactly what caused the error anymore. i was not using any framework, but i was rendering server side. i do remember that what irked me was not the lack of properly serialized virtual dom element, rather the fact it was not an error at all and thus hard to figure out where the error occured. A simple `throw new Error(s)` would have been fine

**Comment by developit** [comment]
Gotcha! Thanks for the additional info.
